/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as MedicalIntelligenceRouteImport } from './routes/medical-intelligence'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as HospitalOpinionsRouteImport } from './routes/hospital-opinions'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as DiseaseEngineRouteImport } from './routes/disease-engine'
import { Route as CommunicationRouteImport } from './routes/communication'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalIntelligenceRoute = MedicalIntelligenceRouteImport.update({
  id: '/medical-intelligence',
  path: '/medical-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalOpinionsRoute = HospitalOpinionsRouteImport.update({
  id: '/hospital-opinions',
  path: '/hospital-opinions',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseaseEngineRoute = DiseaseEngineRouteImport.update({
  id: '/disease-engine',
  path: '/disease-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationRoute = CommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/communication': typeof CommunicationRoute
  '/disease-engine': typeof DiseaseEngineRoute
  '/doctors': typeof DoctorsRoute
  '/documents': typeof DocumentsRoute
  '/finance': typeof FinanceRoute
  '/follow-ups': typeof FollowUpsRoute
  '/hospital-opinions': typeof HospitalOpinionsRoute
  '/hospitals': typeof HospitalsRoute
  '/leads': typeof LeadsRoute
  '/medical-intelligence': typeof MedicalIntelligenceRoute
  '/patients': typeof PatientsRoute
  '/proposals': typeof ProposalsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/communication': typeof CommunicationRoute
  '/disease-engine': typeof DiseaseEngineRoute
  '/doctors': typeof DoctorsRoute
  '/documents': typeof DocumentsRoute
  '/finance': typeof FinanceRoute
  '/follow-ups': typeof FollowUpsRoute
  '/hospital-opinions': typeof HospitalOpinionsRoute
  '/hospitals': typeof HospitalsRoute
  '/leads': typeof LeadsRoute
  '/medical-intelligence': typeof MedicalIntelligenceRoute
  '/patients': typeof PatientsRoute
  '/proposals': typeof ProposalsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/communication': typeof CommunicationRoute
  '/disease-engine': typeof DiseaseEngineRoute
  '/doctors': typeof DoctorsRoute
  '/documents': typeof DocumentsRoute
  '/finance': typeof FinanceRoute
  '/follow-ups': typeof FollowUpsRoute
  '/hospital-opinions': typeof HospitalOpinionsRoute
  '/hospitals': typeof HospitalsRoute
  '/leads': typeof LeadsRoute
  '/medical-intelligence': typeof MedicalIntelligenceRoute
  '/patients': typeof PatientsRoute
  '/proposals': typeof ProposalsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administration'
    | '/communication'
    | '/disease-engine'
    | '/doctors'
    | '/documents'
    | '/finance'
    | '/follow-ups'
    | '/hospital-opinions'
    | '/hospitals'
    | '/leads'
    | '/medical-intelligence'
    | '/patients'
    | '/proposals'
    | '/reports'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administration'
    | '/communication'
    | '/disease-engine'
    | '/doctors'
    | '/documents'
    | '/finance'
    | '/follow-ups'
    | '/hospital-opinions'
    | '/hospitals'
    | '/leads'
    | '/medical-intelligence'
    | '/patients'
    | '/proposals'
    | '/reports'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/administration'
    | '/communication'
    | '/disease-engine'
    | '/doctors'
    | '/documents'
    | '/finance'
    | '/follow-ups'
    | '/hospital-opinions'
    | '/hospitals'
    | '/leads'
    | '/medical-intelligence'
    | '/patients'
    | '/proposals'
    | '/reports'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministrationRoute: typeof AdministrationRoute
  CommunicationRoute: typeof CommunicationRoute
  DiseaseEngineRoute: typeof DiseaseEngineRoute
  DoctorsRoute: typeof DoctorsRoute
  DocumentsRoute: typeof DocumentsRoute
  FinanceRoute: typeof FinanceRoute
  FollowUpsRoute: typeof FollowUpsRoute
  HospitalOpinionsRoute: typeof HospitalOpinionsRoute
  HospitalsRoute: typeof HospitalsRoute
  LeadsRoute: typeof LeadsRoute
  MedicalIntelligenceRoute: typeof MedicalIntelligenceRoute
  PatientsRoute: typeof PatientsRoute
  ProposalsRoute: typeof ProposalsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-intelligence': {
      id: '/medical-intelligence'
      path: '/medical-intelligence'
      fullPath: '/medical-intelligence'
      preLoaderRoute: typeof MedicalIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital-opinions': {
      id: '/hospital-opinions'
      path: '/hospital-opinions'
      fullPath: '/hospital-opinions'
      preLoaderRoute: typeof HospitalOpinionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disease-engine': {
      id: '/disease-engine'
      path: '/disease-engine'
      fullPath: '/disease-engine'
      preLoaderRoute: typeof DiseaseEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication': {
      id: '/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof CommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministrationRoute: AdministrationRoute,
  CommunicationRoute: CommunicationRoute,
  DiseaseEngineRoute: DiseaseEngineRoute,
  DoctorsRoute: DoctorsRoute,
  DocumentsRoute: DocumentsRoute,
  FinanceRoute: FinanceRoute,
  FollowUpsRoute: FollowUpsRoute,
  HospitalOpinionsRoute: HospitalOpinionsRoute,
  HospitalsRoute: HospitalsRoute,
  LeadsRoute: LeadsRoute,
  MedicalIntelligenceRoute: MedicalIntelligenceRoute,
  PatientsRoute: PatientsRoute,
  ProposalsRoute: ProposalsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
